backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# when using a custom proxy server port
local_backend: true

# Folder for storing media content
media_folder: "/Images/cms"


editor:
  preview: false

collections:
  - name: "article" # Used in routes, e.g., /admin/collections/blog
    label: "Article" # Used in the UI
    folder: "articles" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image", required: false, default: "/Images/cms/ArticlePlaceholder.jpg"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "oclareArticle.njk"}
      - {label: "Tags", name: "tags", widget: "hidden", allow_add: false, default: ["post"]}
  
  - name: "pages"
    label: "Pages"
    files:  
    - label: "Homepage"
      name: "homepage"
      file: "/index.md"
      create: false
      delete: false
      fields:
        - {label: "Layout", name: "layout", widget: "hidden", default: "oclareHome.njk"}
        - {label: "Title", name: "title", widget: "hidden", default: "Homepage"}
        - {label: "Title Image", name: "image", widget: "image"}        
        - {label: "Body", name: "body", widget: "markdown"}
  
  - name: "documentation" # Used in routes, e.g., /admin/collections/blog
    label: "Documentation" # Used in the UI
    folder: "documentation" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{title}}" # Filename template
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Position", name: "position", widget: "number", valueType: "int", min: 1, max: 1000}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "oclareDocIndex.njk"}
      - {label: "Tags", name: "tags", widget: "hidden", allow_add: false, default: ["documentation"]}
      
